---
- name: Copy the iperf3_exporter systemd service file
  template:
    src: iperf3_exporter.service.j2
    dest: /etc/systemd/system/iperf3_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart iperf3_exporter