---
- name: Create the iperf3_exporter group
  group:
    name: "{{ _iperf3_exporter_system_group }}"
    state: present
    system: true
  when: _iperf3_exporter_system_group != "root"

- name: Create the iperf3_exporter user
  user:
    name: "{{ _iperf3_exporter_system_user }}"
    groups: "{{ _iperf3_exporter_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /
  when: _iperf3_exporter_system_user != "root"

- block:
    - name: Download iperf3_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/edgard/iperf3_exporter/releases/download/v{{ iperf3_exporter_version }}/iperf3_exporter-{{ iperf3_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/iperf3_exporter-{{ iperf3_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        checksum: "sha256:{{ iperf3_exporter_checksum }}"
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack iperf3_exporter binary
      become: false
      unarchive:
        src: "/tmp/iperf3_exporter-{{ iperf3_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/iperf3_exporter-{{ iperf3_exporter_version }}.linux-{{ go_arch }}/iperf3_exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate iperf3_exporter binaries
      copy:
        src: "/tmp/iperf3_exporter-{{ iperf3_exporter_version }}.linux-{{ go_arch }}/iperf3_exporter"
        dest: "{{ _iperf3_exporter_binary_install_dir }}/iperf3_exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart iperf3_exporter
      when: not ansible_check_mode
  when: iperf3_exporter_binary_local_dir | length == 0

- name: propagate locally distributed iperf3_exporter binary
  copy:
    src: "{{ iperf3_exporter_binary_local_dir }}/iperf3_exporter"
    dest: "{{ _iperf3_exporter_binary_install_dir }}/iperf3_exporter"
    mode: 0755
    owner: root
    group: root
  when: iperf3_exporter_binary_local_dir | length > 0
  notify: restart iperf3_exporter

