---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    iperf3_exporter_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- name: Naive assertion of proper listen address
  assert:
    that:
      - "':' in iperf3_exporter_web_listen_address"

- name: Check if iperf3_exporter is installed
  stat:
    path: "{{ _iperf3_exporter_binary_install_dir }}/iperf3_exporter"
  register: __iperf3_exporter_is_installed
  check_mode: false
  tags:
    - iperf3_exporter_install

- name: Gather currently installed iperf3_exporter version (if any)
  command: "{{ _iperf3_exporter_binary_install_dir }}/iperf3_exporter --version"
  changed_when: false
  register: __iperf3_exporter_current_version_output
  check_mode: false
  when: __iperf3_exporter_is_installed.stat.exists
  tags:
    - iperf3_exporter_install
    - skip_ansible_lint

- block:
    - name: Get latest release
      uri:
        url: "https://github.com/edgard/iperf3_exporter/releases/latest"
        method: GET
        return_content: true
        status_code: 200
        body_format: json
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      no_log: "{{ not lookup('env', 'MOLECULE_DEBUG') | bool }}"
      register: _latest_release
      until: _latest_release.status == 200
      retries: 5

    - name: "Set iperf3_exporter version to {{ _latest_release.json.tag_name[1:] }}"
      set_fact:
        iperf3_exporter_version: "{{ _latest_release.json.tag_name[1:] }}"
  when:
    - iperf3_exporter_version == "latest"
    - iperf3_exporter_binary_local_dir | length == 0
  delegate_to: localhost
  run_once: true

- block:
    - name: Get checksum list from github
      set_fact:
        _checksums: "{{ lookup('url', 'https://github.com/edgard/iperf3_exporter/releases/download/v' + iperf3_exporter_version + '/sha256sums.txt', wantlist=True) | list }}"
      run_once: true

    - name: "Get checksum for {{ go_arch }} architecture"
      set_fact:
        iperf3_exporter_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when:
        - "('linux-' + go_arch + '.tar.gz') in item"
  when: iperf3_exporter_binary_local_dir | length == 0

